export const ORDER_FILTER_KEYS = {
    name: "name",
    surname: "surname",
    email: "email",
    phone: "phone",
    age: "age",
    course: "course",
    course_format: "course_format",
    course_type: "course_type",
    status: "status",
    group: "group",
    startDate: "startDate",
    endDate: "endDate",
    onlyMine: "onlyMine",
} as const;
export const initialOrderFilters = {
    name: "",
    surname: "",
    email: "",
    phone: "",
    age: "",
    course: "",
    course_format: "",
    course_type: "",
    status: "",
    group: "",
    startDate: "",
    endDate: "",
    onlyMine: "",
};
